export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_LOAD_SUCCESS = "LOGIN_LOAD_SUCCESS";
export const LOGIN_LOAD_FAIL = "LOGIN_LOAD_FAIL";

export const LOGOUT = "LOGOUT";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_LOAD_SUCCESS = "REGISTER_LOAD_SUCCESS";
export const REGISTER_LOAD_FAIL = "REGISTER_LOAD_FAIL";

export const FLIGHTS_LOADING = "FLIGHTS_LOADING";
export const FLIGHTS_LOAD_SUCCESS = "FLIGHTS_LOAD_SUCCESS";
export const FLIGHTS_LOAD_FAIL = "FLIGHTS_LOAD_FAIL";

export const BOOKINGS_LOADING = "BOOKINGS_LOADING";
export const BOOKINGS_LOAD_SUCCESS = "BOOKINGS_LOAD_SUCCESS";
export const BOOKINGS_LOAD_FAIL = "BOOKINGS_LOAD_FAIL";
